### ISSUE TITLE
Eslint-plugin-decorator package removed from NPM (Traceur Template)

### ISSUE THREAD

**Issue by brh55** [TheVelourFog/slush-angular2#2]
Looks like the Eslint decorator has been removed from NPM, which is causing some issues.

Also an unrelated issue, I was getting issues scaffolding the Traceur-based App during the build:bundle task. Issues regarding the baseurl and systemjs.

**Comment by RyanMetin** [comment]
Thanks for the heads up.

I'm travelling abroad right now among some very rubbish internets, so I'm just going to take out the Traceur bit for now.
